### PR TITLE
Complete Typescript typings

### LINKED ISSUE #12: [Feature Request] [Minor Improvement] Typescript Typings
I personally would benefit from having typescript type definitions for `vuex-oidc`. 

If I ever get around to making it I will submit a PR 👍

### PR DESCRIPTION
**Pull request by alastairs**
I ran into #42 after spending a while trying to write my own typings for vuex-oidc. Unfortunately I can't update that PR itself, so I've pulled @luvies branch into my own fork and added a further commit for the comments left on the PR by @perarnborg. 

It seems that the original PR has gone quiet, so I hope this will expedite the release of these definitions.

Closes #12.

### CODE REVIEW

**Comment by alastairs** [comment]
(Updating now with fixed duplicate definitions.)

**Comment by perarnborg** [comment]
Excellent! I will look at this within short!

**Comment by perarnborg** [comment]
There are some changes in the library again that need corresponding typing updates, but this looks great! Thank you @luvies and @alastairs for contributing!

**Comment by perarnborg** [comment]
I will see if I can update the trackings, but I am merging this for now.

**Pull request merged**
