### PR TITLE
small change to make native ESM loading working

### PR DESCRIPTION
**Pull request by BWalti**
May I suggest a slight modification - most probably without negative impact?

I did this change locally to get a vue#3.0.0-rc.5 (with 

- vuex#4.0.0-beta.4, 
- vue-router#4.0.0-beta.4, 
- vuex-oidc#3.7.0 and 
- oidc-client#1.10.1

) app on vitejs working.

I'm not completely sure about this as I'm still a JS noob, especially if it gets down to the bundling / tooling stuff :)

### CODE REVIEW

**Comment by perarnborg** [comment]
This would indeed not have any negative impact. Do you have any insight in why this works better with native ESM loading though?

**Comment by BWalti** [comment]
sadly not yet. I tried to use oidc-client from a vitejs/vue app without vuex-oidc in the first place and had to use this alternative import statement to fix issues at that time, therefore I tried it in vuex-oidc too.

In my understanding it has to do with how oidc-client was historically not built to natively support ESM (something they want to address in v2.0+). How / why rollup manages to load the module correctly when using the suggested syntax - no idea,

**Comment by BWalti** [comment]
maybe it's related to either: https://github.com/IdentityModel/oidc-client-js/pull/757 or https://github.com/IdentityModel/oidc-client-js/issues/515

But as initially stated: I am very new to this JS bundling / tooling world

**Comment by perarnborg** [comment]
Ok, I see! Fair enough, Let’s merge this!

**Comment by perarnborg** [comment]
Published in v3.7.2

**Comment by BWalti** [comment]
thanks a lot!
Using this new version I can confirm that it solves my issue. (do we really have to understand why? :) )
Thanks again!

**Pull request merged**
